# Generated by Django 3.2.4 on 2021-06-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blackjack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_decks', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
